# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-30 22:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(default='Description', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Description', max_length=255)),
                ('closed', models.BooleanField(default=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Category')),
            ],
        ),
    ]
