# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-20 02:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
